# Generated by Django 3.2.2 on 2023-12-15 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название мероприятия', max_length=200)),
                ('time_start', models.DateTimeField(null=True)),
                ('time_end', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('max_num_of_participants', models.IntegerField()),
                ('level', models.IntegerField()),
                ('sponsors', models.CharField(max_length=200)),
                ('meaner', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='registration.user')),
            ],
        ),
    ]
