# Generated by Django 5.0 on 2023-12-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='events.tag'),
        ),
    ]
