# Generated by Django 5.0 on 2023-12-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_competition_tag_competition_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='tag',
            field=models.ManyToManyField(to='events.tag'),
        ),
    ]
