# Generated by Django 3.2.2 on 2023-12-15 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Имя Фамилия', max_length=200)),
                ('email', models.CharField(help_text="user's email", max_length=200)),
                ('phone', models.CharField(help_text="User's phone", max_length=200)),
                ('password', models.IntegerField()),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DR', 'DevRel'), ('U', 'User')], default='U', max_length=2)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('level', models.CharField(max_length=50, null=True)),
                ('competitions', models.CharField(max_length=200, null=True)),
                ('is_agree_to_mailing', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.SET, to='registration.user')),
            ],
        ),
    ]