# Generated by Django 5.0 on 2023-12-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
