# Generated by Django 5.0 on 2023-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_user_username_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
